name: CI Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install project in Docker
      run: docker-compose up -d --build
    - name: Install Composer
      run: docker-compose exec app composer install
    - name: Copy phpUnit
      run: cp phpunit.xml.dist phpunit.xml
    - name: Run tests
      run: docker-compose exec app ./vendor/bin/phpunit
